### ISSUE TITLE
The `ember generate <entity-name>` command requires an entity name to be specified.

### ISSUE THREAD

**Issue by oskarrough** [hiwhi/ember-cli-cloudinary#1]
Hi, when I attempt to `ember install ember-cli-cloudinary` in a fresh 2.4.1 install I get:

```
The `ember generate <entity-name>` command requires an entity name to be specified.
```

Any ideas?

**Comment by mileszim** [comment]
Thanks for letting me know about this! Apologies on the delay to fix it. It is fixed in the latest release.
