### ISSUE TITLE
Add publicId option to enable an existing image to be updated

### ISSUE THREAD

**Issue by aonawale** [hiwhi/ember-cli-cloudinary#11]
Presently there is no way to edit an already uploaded image using the `cloudinary-direct-file` component. Cloudinary accepts an optional public_id which if provided overwrites an existing image with that public_id.

**Comment by waelbeso** [comment]
what is the use case of overwrites an existing image ?

**Comment by aonawale** [comment]
Say for example you want to update the profile image of users in your application. When they upload an image the first time, you save their Cloudinary image public_id in their profile; If they decide to change their profile image later, then the reasonable thing to do is to overwrite the existing image with the new one they are uploading while keeping the same image public_id.

**Comment by waelbeso** [comment]
the cloudinary api did not support this method as I know you can remove the old profile image by id and it's our responsibility to update our app.

**Comment by mileszim** [comment]
I'm closing this for now, as this seems straightforward enough for you to implement a PR. If you do that, happy to accept it. Thanks :)
