### ISSUE TITLE
No source map is available. Ember-cli asks for it 

### ISSUE THREAD

**Issue by waelbeso** [hiwhi/ember-cli-cloudinary#3]
jest after fresh installation,  and the {{cloudinary-image }} never appeared in the page

Warning: ignoring input sourcemap for bower_components/cloudinary-jquery-file-upload/cloudinary-jquery-file-upload.js because ENOENT: no such file or directory, open '/Users/wael/Desktop/ftrina.clint/ftrina/tmp/source_map_concat-input_base_path-zn9K3dyM.tmp/0/bower_components/cloudinary-jquery-file-upload/cloudinary-jquery-file-upload.js.map'

**Comment by mileszim** [comment]
That's an odd one! Which version of ember-cli are you using? I'm having trouble reproducing this.

**Comment by tocker** [comment]
Remove the last line in `bower_components/cloudinary-jquery-file-upload/cloudinary-jquery-file-upload.js`:

```
//# sourceMappingURL=cloudinary-jquery-file-upload.js.map
```

That map file was not included in the bower package. Sorry! We'll fix it soon.

**Comment by mileszim** [comment]
thanks @tocker!

**Comment by waelbeso** [comment]
mission accomplished ;)
thanks maileszim & tocker,

**Comment by mileszim** [comment]
@tocker what's the status on updating the jquery package on your end? Waiting to close this out until I can update the version number for it in bower.json

**Comment by waelbeso** [comment]
@mileszim hope you can update the README and add some examples for the validation.

in the last few days, I added some useful methods that I'd like to share with you. 
-  Binding 'style' attribute 
-  Binding 'accept' attribute 
-  Add event 'OnFileChange'

all works fine with me in EMBER 2.5 , cloudinary-jquery-file-upload 2.1.0

jest miss the jquery.fileupload-validate integration .

**Comment by mileszim** [comment]
@waelbeso can you open a PR with your additions? I'd love to take a look

**Comment by waelbeso** [comment]
@mileszim of course i will, and will love to hear your feedback ;)

**Comment by tocker** [comment]
Fixed in Cloudinary version 2.1.1

**Comment by mileszim** [comment]
you rock @tocker, thanks!

**Comment by waelbeso** [comment]
@tocker i have to tell you big thanks.

**Comment by waelbeso** [comment]
what about my update ? i will go on in defiant branch or we can change to default ?
